################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_PTMP "ptmp")
    if (PC_PTMP_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_PTMP_CFLAGS} ${PC_PTMP_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_PTMP_INCLUDE_HINTS ${PC_PTMP_INCLUDE_DIRS} ${PC_PTMP_INCLUDE_DIRS}/*)
        set(PC_PTMP_LIBRARY_HINTS ${PC_PTMP_LIBRARY_DIRS} ${PC_PTMP_LIBRARY_DIRS}/*)
    endif(PC_PTMP_FOUND)
endif (NOT MSVC)

find_path (
    PTMP_INCLUDE_DIRS
    NAMES ptmp/api.h
    HINTS ${PC_PTMP_INCLUDE_HINTS}
)

find_library (
    PTMP_LIBRARIES
    NAMES ptmp
    HINTS ${PC_PTMP_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    PTMP
    REQUIRED_VARS PTMP_LIBRARIES PTMP_INCLUDE_DIRS
)
mark_as_advanced(
    PTMP_FOUND
    PTMP_LIBRARIES PTMP_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
