The following ABNF grammar defines the Trigger Primitive Queue Codec:

    tpq     = hello *( query | result ) [ goodbye ]
    hello   = C:HELLO  ( S:HELLO-OK / S:INVALID / S:FAILED )
    query   = C:QUERY    ( S:RESULT / S:INVALID / S:FAILED )
    heartbeat = C:PING S:PONG
    goodbye = C:GOODBYE ( S:GOODBYE-OK / S:INVALID / S:FAILED )

    ;  Greet a server.

    HELLO           = signature %d1 nickname
    signature       = %xAA %xA0             ; two octets
    nickname        = string                ; Client nickname

    ;  Declare TP input coverage supported by a server.

    COVERAGE        = signature %d2 detmask
    detmask         = number-8              ; Detector ID mask

    ;  Request TPSets

    QUERY           = signature %d3 seqno tstart tspan detmask timeout
    seqno           = number-4              ; A message sequence number.
    tstart          = number-8              ; A tstart value.
    tspan           = number-8              ; A tspan value.
    detmask         = number-8              ; Detector ID mask
    timeout         = number-4              ; Timeout in msec

    ;  No description

    RESULT          = signature %d4 seqno status payload
    seqno           = number-4              ; A message sequence number.
    status          = number-2              ; The 3-digit status code related to the result.
    payload         = msg                   ; A msg holding one frame per TPSet.

    ;  No description

    PING            = signature %d5

    ;  No description

    PONG            = signature %d6

    ;  No description

    GOODBYE         = signature %d7

    ;  No description

    GOODBYE-OK      = signature %d8

    ;  Command failed for some specific reason

    ERROR           = signature %d9 status reason
    status          = number-2              ; 3-digit status code
    reason          = string                ; Printable explanation

    ; A msg is zero or more distinct frames
    msg             = *frame

    ; Strings are always length + text contents
    string          = number-1 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
