/*  =========================================================================
    tpquery_classes - private header file

    Copyright 2019.  May use and distribute according to LGPL v3 or later.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef TPQUERY_CLASSES_H_INCLUDED
#define TPQUERY_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/tpquery.hpp"

//  Opaque class structures to allow forward references

//  Extra headers

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef TPQUERY_BUILD_DRAFT_API

//  Self test for private classes
TPQUERY_PRIVATE void
    tpquery_private_selftest (bool verbose, const char *subtest);

#endif // TPQUERY_BUILD_DRAFT_API

#endif
